[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[window]
dynamic_padding = true

[window.padding]
x = 5

[font]
size = 10

[font.normal]
family = "IBM Plex Mono"
style = "Regular"

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.selection]
text = "#282828"
background = "#ebdbb2"

[cursor]
style = "Block"
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"
